### ISSUE TITLE
Support priorityClassName in the chart 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/backup-restore-operator#114]
This is an enhancement to the chart, and it add the option for setting a `priorityClassName` on the deployment. 

See Kubernetes documentation for more info: 
https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/

**Comment by jiaqiluo** [comment]
waiting for 

- [ ] cutting a release in the rancher/backup-restore-operator repo
- [ ] cutting a new chart release in the rancher/charts repo

**Comment by jiaqiluo** [comment]
can be tested on rancher-backup:`2.0.0+up2.0.0-rc2` in rancher:`master-head`

**Comment by sowmyav27** [comment]
**On master-head commit id: `d44698d`**

- Rancher backups version installed - `2.0.0+up2.0.0-rc2`
```
affinity: {}
global:
  cattle:
    systemDefaultRegistry: ''
  kubectl:
    repository: rancher/kubectl
    tag: v1.20.2
image:
  repository: rancher/backup-restore-operator
  tag: v2.0.0-rc2
nodeSelector: {}
persistence:
  enabled: false
  size: 2Gi
  storageClass: '-'
  volumeName: ''
priorityClassName: ''
```
