### ISSUE TITLE
[Backport] Support priorityClassName in the chart

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/backup-restore-operator#115]
https://github.com/rancher/backup-restore-operator/issues/114

**Comment by jiaqiluo** [comment]
Can be tested in chart rancher-backup `1.2.0-rc2`

**Comment by sowmyav27** [comment]
On 2.5-head commit id: `defd81cd`

- Rancher backup charts version: `v1.2.0-rc3`
```
affinity: {}
global:
  cattle:
    systemDefaultRegistry: ''
  kubectl:
    repository: rancher/kubectl
    tag: v1.20.2
image:
  repository: rancher/backup-restore-operator
  tag: v1.2.0-rc3
nodeSelector: {}
persistence:
  enabled: false
  size: 2Gi
  storageClass: '-'
  volumeName: ''
priorityClassName: ''
```
- While deploying rancher backups give the `priorityClassName: high-priority`.
- Backup restore pod Fails to deploy with error: `Pods "rancher-backup-64f8866b44-" is forbidden: no PriorityClass with name high-priority was found`
- Created a priority class using [this](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#example-priorityclass) doc 
- The pod come sup Active.
