### ISSUE TITLE
[Backport] Backup CR with s3.folder does not allow multiple path components

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/backup-restore-operator#121]
https://github.com/rancher/backup-restore-operator/issues/63

**Comment by jiaqiluo** [comment]
Can be tested in chart rancher-backup `1.2.0-rc2`

**Comment by anupama2501** [comment]
Verified on 2.5-head commit: 0713103

- Installed rancher backup `rancher-backup:1.2.0-rc3`
- Verified by creating a backup with the values of S3:

```
  storageLocation:
    s3:
      bucketName: au-s3bucket
      credentialSecretName: anupama-s3
      credentialSecretNamespace: default
      endpoint: s3.us-west-2.amazonaws.com
      folder: rancher.example.com/rancher-backup
```

- Verified backup created in S3
