### ISSUE TITLE
Custom Resources with empty Status fail restore

### ISSUE THREAD

**Issue by snasovich** [rancher/backup-restore-operator#135]
Steps to reproduce:
1. Have a backup containing a Custom Resource with empty `status` with Custom Resource Definition actually defining status. For example, at this time `digitaloceanmachinetemplates.rke-machine.cattle.io` can be used as per https://github.com/rancher/rancher/issues/33684
2. Attempt to restore from this backup.

Result:
Restore keeps failing with something like this present in log:
```log
[INFO 2021/07/18 22:11:58] Updating status subresource for "do-to-backup-1-sergey-backup-test-1" of type rke-machine.cattle.io/v1, Resource=digitaloceanmachinetemplates 
[ERRO 2021/07/18 22:11:58] Error restoring resource do-to-backup-1-sergey-backup-test-1 of type rke-machine.cattle.io/v1, Resource=digitaloceanmachinetemplates:
restoreResource: err updating status resource DigitaloceanMachineTemplate.rke-machine.cattle.io "do-to-backup-1-sergey-backup-test-1" is invalid:
status: Invalid value: "null": status in body must be of type object: "null"
```

Expected Behavior:
Custom Resource is restored successfully

Note:
If preparing/massaging backup manually for testing, ensure `filters/statussubresource.json` is included in the backup and lists the resource with the expected status as it's what is used by restore to determine whether attempt is made to restore status.

**Comment by snasovich** [comment]
@jiaqiluo , could you please validate this one? Thank you.

**Comment by jiaqiluo** [comment]
The fix is validated in rancher master-head 2b156fd with the chart `rancher-backup-2.0.0+up2.0.0-rc7`

Note that we need to add the following items to the `resourceSelectors` section of the default `resourceSet` to support the backup of `digitaloceanmachinetemplates` which is used by Fleet. 
```
# Added for v2 provisioning
- apiVersion: apiextensions.k8s.io/v1
  kindsRegexp: .
  resourceNameRegexp: provisioning.cattle.io$|rke-machine-config.cattle.io$|rke-machine.cattle.io$|rke.cattle.io$
- apiVersion: provisioning.cattle.io/v1
  kindsRegexp: .
- apiVersion: rke-machine-config.cattle.io/v1
  kindsRegexp: .
- apiVersion: rke-machine.cattle.io/v1
  kindsRegexp: .
- apiVersion: rke.cattle.io/v1
  kindsRegexp: .
- apiVersion: apiextensions.k8s.io/v1
  kindsRegexp: .
  resourceNameRegexp: cluster.x-k8s.io$
- apiVersion: cluster.x-k8s.io/v1alpha4
  kindsRegexp: .`
# The below will backup unnecessary default-token-... secret
- apiVersion: v1
  kindsRegexp: ^secrets$
  namespaces:
  - fleet-default
```

Steps:
- run rancher in HA mode
- provision a RKE2 cluster with Digital Ocean as the node provider 
- install the rancher-backup app 
- edit the default resourceSet to add the above section 
- make a backup 
- check the backup file to confirm that the `digitaloceanmachinetemplates` CR exists 
- stop rancher 
- restore the backup on a new HA cluster 

Results:
- the restore is finished successfully 
- the `digitaloceanmachinetemplates` CR is restored 
- Rancher continues working
