### ISSUE TITLE
Ability of specifying endpointCA via configmap/secret - in k8s native way

### ISSUE THREAD

**Issue by dmpe** [rancher/backup-restore-operator#168]
Hi, 
specifying `endpointCA` shall be improved. Currently, it expects a base64 encoded string, which is everything other than a usual approach of giving configmap/secret in the helm chart. I am not sure why it is done like that, but we shall be able to use a more native k8s way. 

So instead of s3 being stored as key
```
s3:
  enabled: true
  credentialSecretName: "rancher-backup-s3"
  credentialSecretNamespace: "cattle-resources-system"
  region: "netapp"
  bucketName: "rancher-backup-operator-production"
  endpoint: "s3"
  endpointCA: "<base64> encoded string"
```

we shall use either an environmental variable or (best) volume like it is described here https://kubernetes.io/docs/concepts/configuration/secret/#projection-of-secret-keys-to-specific-paths

```
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
      items:
      - key: username
        path: my-group/my-username
```

The alternative would be to say:

```
endpointCASecretName: "name of secret where cacerts are stored/read from"
```

Btw. I also think certs shall be done via configmap, i.e. use `env` key in `containers` (taken from [here](https://kubernetes.io/docs/concepts/configuration/configmap/#configmaps-and-pods)

```
      env:
        - name: endpointCA
          valueFrom:
            configMapKeyRef:
              name: endpointCAconfigmap-name
              key: cacerts
```

Thanks.
