### ISSUE TITLE
retentionCount does not delete expired objects

### ISSUE THREAD

**Issue by cest-pas-faux** [rancher/backup-restore-operator#185]
Hi,

- Dedicated EKS cluster v1.21.5-eks-bc4871b
- Rancher 2.6.3 installed by Helm
- Rancher-backup 2.0.1 installed by Helm

I'm looking for advices on this bug I'm encountering.
As stated on the configs below, I defined a retentionCount for the backup files in order to tidy up and avoid consuming too much space on the s3 bucket

```yaml
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: hourly-backup
spec:
  resourceSetName: rancher-resource-set
  schedule: "@every 1h"
  retentionCount: 24
---
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: daily-backup
spec:
  resourceSetName: rancher-resource-set
  schedule: "@every 24h"
  retentionCount: 30
```

The backups are working well, but the retentionCount does not delete the older files : 

![image](https://user-images.githubusercontent.com/23448243/148591966-d6fe7038-efe0-4a9e-ac19-c17f20056883.png)

Thanks in advance.
