### ISSUE TITLE
Restore fails with "failed to check s3 bucket" error

### ISSUE THREAD

**Issue by laurie-kepford** [rancher/backup-restore-operator#203]
I am trying to restore a backup to a new cluster. Using instructions here: https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/.  Restore is failing with this error:

```
INFO[2022/03/20 16:50:50] invoking set s3 service client                s3-accessKey="base64encodedaccess key=" s3-bucketName=mybucket s3-endpoint=s3.us-west-2.amazonaws.com s3-endpoint-ca= s3-folder= s3-region=us-west-2
ERRO[2022/03/20 16:50:50] error syncing 'restore-migration': handler restore: failed to check s3 bucket:mybucket, err:400 Bad Request, requeuing
```

Backups are in an s3 bucket. I have verified that I am using the same credentials that were used to create the backup,  And the path to the backup is correct.  What else could be wrong?

**Comment by superseb** [comment]
What version was and is used (if they are different)?

Also please share the exact config used (redacted) and I assume Amazon S3 is used as storage.

**Comment by laurie-kepford** [comment]
The old Rancher is a **docker install, Version 2.6.2.** The new Cluster is a **EKS cluster, K8s 1.20.**  Yes, S3 is used for storage.  I did not install rancher on the new cluster.

It's not a large installation, only one downstream cluster.
What would happen if I did the following:

- Install rancher on the new cluster.
- Remove rancher from the downstream cluster
- Import the downstream cluster into the new rancher?

What would be the down side of doing it that way?  What kinds of things would I likely loose and have to re-create?

My Config for creating the restore:

```
apiVersion: resources.cattle.io/v1
kind: Restore
metadata:
  name: restore-migration
spec:
  backupFilename: nightly-65eff810-5027-4527-b0ab-81ac234768f0-2022-03-20T00-00-00Z.tar.gz
  prune: false
  storageLocation:
    s3:
      credentialSecretName: s3-creds
      credentialSecretNamespace: default
      bucketName: rancher-backups
      region: us-west-2
      endpoint: s3.us-west-2.amazonaws.com
```
S3 Secret

```
apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
type: Opaque
stringData:
  accessKey: ACCESSKEYBASE64ENCODED
  secretKey: SECRETKEYBASE64ENCODED
```
