### ISSUE TITLE
Remove ununsed/un-updated numRetries field from Backup CR Status

### ISSUE THREAD

**Issue by sowmyav27** [rancher/backup-restore-operator#23]
**On master-head - commit id: `731b33e1a776`**

- Create a restore CR from a backup file. Give an invalid bucketname.
- Restore will fail and the CR will be seen stuck in "Error"
- create another restore CR. With valid details
- The restore starts and completes. Rancher comes up successfully.
- On the failed restore CR i see numRetries: 0 and count NOT increasing. But i see the retries happening in the backup-restore-operator logs.

```
status:
  backupSource: ""
  conditions:
  - lastUpdateTime: "2020-09-03T17:51:25Z"
    message: 'failed to download s3 backup: no backups found'
    reason: Error
    status: "False"
    type: Reconciling
  - lastUpdateTime: "2020-09-03T17:45:57Z"
    message: Retrying
    status: Unknown
    type: Ready
  numRetries: 0
  observedGeneration: 0
  restoreCompletionTs: ""
  summary: ""
```

**Expected:**
Remove field numRetries
