### ISSUE TITLE
NetworkPolicy block ingress traffic from external ingress controller.

### ISSUE THREAD

**Issue by intonet** [rancher/backup-restore-operator#257]
I have installed ingress controller outside cattle-system namespace. After install backup chart rancher response witch 504 code (gateway timeout).  

I put ingress section to allow ingress traffic from all.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    argocd.argoproj.io/instance: rancher-backup--ams-one-core-dev-01
  name: rancher-backup-default-allow-all
  namespace: cattle-system
spec:
  egress:
    - {}
  ingress:
    - {}  
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
```
