### ISSUE TITLE
Backup restore operator fails to install when persistence storage is enabled with storage class set to "local-path"

### ISSUE THREAD

**Issue by soumyalj** [rancher/backup-restore-operator#27]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
1. Install local-path-provisioner 
https://github.com/rancher/local-path-provisioner
2. Install backup restore operator chart in rancher with persistence enable=true and storage class = "local-path"
```
affinity: {}
image:
  repository: rancher/backup-restore-operator
  tag: v0.0.1-rc10
nodeSelector: {}
persistence:
  enabled: true
  size: 2Gi
  storageClass: 'local-path'
  volumeName: ''
s3:
  bucketName: rancherbackups
  credentialSecretName: creds
  credentialSecretNamespace: ''
  enabled: false
  endpoint: s3.us-west-2.amazonaws.com
  endpointCA: base64 encoded CA cert
  folder: base folder
  region: us-west-2
tolerations: []




```

**Result:**
Backup restore operator fails to install with an exit code; 123

![Screen Shot 2020-09-10 at 10 12 46 AM](https://user-images.githubusercontent.com/18536626/92769849-39be6880-f34e-11ea-9174-49f097f82680.png)

Only backup-restore-operator-crd is installed 

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head(master-198ec5bdf52d3)
- Installation option (single install/HA): HA

**Comment by soumyalj** [comment]
Validated with master-head(master-ab6598e5add2414d9f58244300c3fa28072cca8e-head)
Steps:
1. Install local-path-provisioner
https://github.com/rancher/local-path-provisioner
2. Install backup restore operator chart in rancher with persistence enable=true and storage class = "local-path"

```
affinity: {}
image:
  repository: rancher/backup-restore-operator
  tag: v0.0.1-rc11
nodeSelector: {}
persistence:
  enabled: true
  size: 2Gi
  storageClass: 'local-path'
  volumeName: ''
s3:
  bucketName: rancherbackups
  credentialSecretName: creds
  credentialSecretNamespace: ''
  enabled: false
  endpoint: s3.us-west-2.amazonaws.com
  endpointCA: base64 encoded CA cert
  folder: base folder
  region: us-west-2
tolerations: []

```

Backup-restore-operator chart gets installed successfully.
![Screen Shot 2020-09-10 at 5 53 30 PM](https://user-images.githubusercontent.com/18536626/92834236-a2c5d080-f38e-11ea-9336-e6eeb75b28a5.png)
