### ISSUE TITLE
Failing backup with miss-leading error message.

### ISSUE THREAD

**Issue by lalyos** [rancher/backup-restore-operator#57]
I Was trying to create a backup to an AWS s3 bucket. The backup stuck in retry state. Iwas checking for error messages in the pod log"

```
handler backups: failed to check s3 bucket:rancher-backups-xxx, err:Head https://rancher-backups-xxx.s3.dualstack.eu-west-1.amazonaws.com/: 301 response missing Location header, requeuing 
```

My backup CRD did contain the loaction:
```
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: s3-backup-demo
spec:
  storageLocation:
    s3:
      ...
      region: eu-west-1
      endpoint: s3.eu-west-1.amazonaws.com

```

After a while I relized the bucket was in a different region, so it was clearly miss-configured, but it wasn't obvious from the error message above.

## Solution:

- just use this issue as refence, so if somebody is searching for the error text can find the solution
- provide a hint in the error message to check for the bucket location

## Background

Unfortunately minio-go uses string based errors, so it can only be string-matched ... Furthermore seems like the error message is not coming from minio directly, but from the aws-sdk-go library. Actually the s3 api sends a redirect (hence the 301) but that is ignore by the official sdk:
https://github.com/aws/aws-sdk-go/issues/356

> The SDK should not be retrying request when they error with this request. The 301 error returned is due to the request being made to the wrong region. The Go SDK does require that the request are made to the correct region.
The redirect provided by S3 is not intended to actually be followed in this case.
