### ISSUE TITLE
[RFE] Backup Operator ignores "*.*" in EncryptionConfiguration

### ISSUE THREAD

**Issue by bvankampen** [rancher/backup-restore-operator#591]
**Rancher Server Setup**
- Rancher version: 2.9.2
- Backup Operator rancher-backup:104.0.1+up5.0.1

**Describe the bug**
If you define `*.*` in the resources of a EncryptionConfiguration for an encrypted backup, nothing gets encrypted. Is this intended behaviour?

**To Reproduce**
1. Create a EncryptionConfiguration:

```yaml
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - "*.*"
    providers:
      - secretbox:
          keys:
            - name: key1
              secret: <REDACTED>
```
2. Create secret with this file as content.
```
kubectl create secret generic encryptionconfig \
    --from-file=./encryption-provider-config.yaml \
    -n cattle-resource-system
```
3. Create a encrypted Rancher backup with the backup operator. 
4. Download the backup, (rename to tar.gz and) extract, inspect the resource json's
5. None of the resource json are encrypted.

**Expected behavior**
All the resources json are encrypted (like when you use `secrets` as resource.
