### ISSUE TITLE
[RFE] Add a cluster metadata mechanism for Backups

### ISSUE THREAD

**Issue by mallardduck** [rancher/backup-restore-operator#612]
# 🚀 Feature Request

This will (hopefully) further solve issues like this: https://github.com/rancher/rancher/issues/47581. 
It's not the first one like this we've gotten and even with this change may not be the last.  
However, until we try we can't say for sure that BRO itself can't make this more clear.  

## Background

When using BRO in the context of Rancher (i.e. Rancher Backups) the delineation between performing an "In-place Restore" and "Migration" can be very important. Currently the onus of understanding that is fully on the User interacting with the backups. This person needs to be well read on the Rancher Backups documentation, understand the state of the cluster when each backup point was created, and how that compares to the current cluster they're interacting with.

This is an easily overlooked aspect of how Rancher Backups is intended to operate. As issues around this come up we adjust documentation the best we can. Rather than continue to "patch via docs" we could implement a more foundational solution to serve as an indicator.

### Is your feature request related to a problem? Please describe.
Not exactly - more about clarifying a process that has some ambiguity.

### Describe the solution you'd like

- BRO team adds a mechanism for Backups to be correlated to the cluster they are created on.
- In turn, that is used to add a status field to the Backup indicating if it's valid for "in-place" restore.
- Finally, the Rancher UI (and CRD list) is updated to add a "In-Place Restore" column to display the status field in the Backups list.

Logically, the UI stuff needs to come last and can be considered a follow up effort. However we may even want/need to split the first two tasks into their own efforts/PRs.

We will need to explore the most effective way to get the results we're logically expecting. Since it's rather easy to dream up a metadata file we add to tars, but then that implies that to know if we can do an in-place we need to read the tar. Which won't scale well.

#### Technical Implementation

1. When backups are created add a new metadata field to contain cluster ID (of some sort),
2. Add a status field to the backup CRD based on if that metadata field matches the current cluster,
    - If the field is unset, status is unknown; or, false with a status condition might be better?
4. Add UI change to display that status field in table.

### Describe alternatives you've considered

While I have considered this idea in the past (a few times over the last few months), none of those ideas were viable as functional options nor worth documenting. At the current time, the only other alternative for solving this issue is adding more docs.

### Additional context

N/A

**Comment by mallardduck** [comment]
Ok - I've taken some time to do triage on this. I feel the momentum so am going to roll with it for a PoC. Leaving a summary of the concept here for team to review and leave feedback. If I complete the PoC and there is feedback, I will incorporate the feedback into the PoC before PR. Otherwise I will send a PR once it's ready.

---

The source of "Cluster ID" used as the origin cluster of a backup will be pulling from `kube-system` `UID`. The reason being is that this should be the most consistent identifier of "this is the same cluster" compared to alternatives.

It will remain consistent to a specific cluster and remain unique to it across proper node recycling processes, IP changes, or name changes. Similarly, it should also be unique per each individual cluster and is not something that will be restored via "normal backups". (Obviously a full etcd based recovery process changes things, these are out side of the scope of BRO and would essentially allow for a cluster to be considered "the same" for BRO context.)

The "Cluster ID" will be stored on each `Backup` at the time the backup is successful. In other words, the same step where the `Backup` resource is updated to identify the name and location of the `tar` file. In the status of the `Backup` we will set a condition to identify if it being valid for in-place restore or not.

**Comment by mallardduck** [comment]
Here is an example of the Status conditions that would be added to backups:

### Verified:
```yaml
  conditions:
    - lastUpdateTime: '2024-10-31T23:07:36Z'
      message: Completed
      status: 'True'
      type: Ready
    - lastUpdateTime: '2024-10-31T23:07:36Z'
      status: 'True'
      type: Uploaded
    - lastUpdateTime: '2024-10-31T23:07:36Z'
      message: Backup has cluster UID attached.
      status: 'True'
      type: HasClusterOrigin
    - lastUpdateTime: '2024-10-31T23:07:36Z'
      message: In-place Restore appears viable.
      status: 'True'
      type: InPlaceRestore
```

### Unverifiable (created before this change, or missing UID on backup)
```yaml
  conditions:
    - lastUpdateTime: '2024-10-31T23:09:11Z'
      message: Completed
      status: 'True'
      type: Ready
    - lastUpdateTime: '2024-10-31T23:09:11Z'
      status: 'True'
      type: Uploaded
    - lastUpdateTime: '2024-10-31T23:09:33Z'
      message: No cluster UID attached to backup.
      status: 'False'
      type: HasClusterOrigin
    - lastUpdateTime: '2024-10-31T23:09:33Z'
      message: Unable to determine if in-place Restore is viable.
      status: 'False'
      type: InPlaceRestore
```

### Not Viable for InPlace Restore (must use Migration proces)

> This was faked by adding the annotation before creating the Backup. Then using the new code after backup was taken successfully.

```yaml
  conditions:
    - lastUpdateTime: '2024-10-31T23:11:38Z'
      message: Completed
      status: 'True'
      type: Ready
    - lastUpdateTime: '2024-10-31T23:11:38Z'
      status: 'True'
      type: Uploaded
    - lastUpdateTime: '2024-10-31T23:12:30Z'
      message: Backup has cluster UID attached.
      status: 'True'
      type: HasClusterOrigin
    - lastUpdateTime: '2024-10-31T23:14:28Z'
      message: In-place Restore does not appear viable.
      status: 'False'
      type: InPlaceRestore
```
