### ISSUE TITLE
Rancher does not get scaled back up if there is an error during restore

### ISSUE THREAD

**Issue by sowmyav27** [rancher/backup-restore-operator#7]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create a secret using `kubectl create secret generic test-encryptionconfig --from-file=./encryptionConfig.yaml -n cattle-resources-system`
- encryptionConfig.yaml  - is similar to the one [here](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#understanding-the-encryption-at-rest-configuration)
- Create some secrets 
- Create a backup CR and give in `EncryptionConfigName`
- Backup is created successfully. And the secrets in the backup are encrypted.
- Create some more secrets in rancher setup
- Now restore from this backup.
- The rancher pods are not scaled up.
- Logs from backup-restore-operator container:

```
INFO[2020/08/27 23:07:43] Will retry pruning resources by removing finalizers in 0s 
INFO[2020/08/27 23:07:43] Retrying pruning resources by removing finalizers 
INFO[2020/08/27 23:07:43] Processing controllerRef apps/v1/deployments/rancher 
INFO[2020/08/27 23:07:43] Scaling up controllerRef apps/v1/deployments/rancher to 0 
```
- Bring back rancher to scale-3
error in restore CR
```
status:
  conditions:
  - lastUpdateTime: "2020-08-27T23:07:25Z"
    message: 'error pruning during restore: [Operation cannot be fulfilled on secrets
      "test-new": StorageError: invalid object, Code: 4, Key: /registry/secrets/p-g7jm4/test-new,
      ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition:
      e3beec7b-6d0d-4578-b021-9c748ed7ca5e, UID in object meta: ]'
    reason: Error
    status: "False"
    type: Reconciling
  - lastUpdateTime: "2020-08-27T23:07:43Z"
    status: "True"
    type: Ready
```
- Notice that `test-new` is NOT available in the rancher setup

**Expected Result:**
Rancher deployment should scale back up when restore is finished.

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head - commit : `5e1b21b931a`
- Installation option (single install/HA): HA
